name: Build Docker Images
on:
  push:
    branches: ['testgh']

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          [
            api,
            app,
            backend,
            indexer-balance,
            indexer-base,
            indexer-events,
            indexer-dex,
            indexer-multichain,
            explorer-selector,
            aggregates,
          ]
      fail-fast: false

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: linux/amd64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker Metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/nearblocks/${{ matrix.service }}
          tags: sha

      - name: Build and push
        uses: docker/build-push-action@v5
        id: docker_build
        with:
          context: .
          file: apps/${{ matrix.service }}/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/nearblocks/${{ matrix.service }}:latest
            ghcr.io/nearblocks/${{ matrix.service }}:${{ steps.meta.outputs.sha }}
          cache-from: type=registry,ref=ghcr.io/nearblocks/${{ matrix.service }}:latest
          cache-to: type=inline

      - name: Output image metadata
        if: success()
        id: output_image
        run: echo "image=${{ steps.meta.outputs.tags }}" >> $GITHUB_ENV
