name: Deploy testnet
on:
  workflow_run:
    workflows: ["Build Docker Images"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.28.0'

      - name: Configure kubectl
        run: |
          echo "${{ secrets.KUBE_CONFIG }}" | base64 -d > kubeconfig
          echo "KUBECONFIG=$(pwd)/kubeconfig" >> $GITHUB_ENV

      - name: Deploy services
        run: |
          services=(api app backend indexer-balance indexer-base indexer-events indexer-multichain explorer-selector aggregates)
          failed_deployments=()

          for service in "${services[@]}"; do
            image_name="ghcr.io/nearblocks/$service:${{ github.event.workflow_run.head_sha }}"
            echo "Updating $service to image $image_name"
            
            kubectl set image deployment/testnet-$service $service=$image_name

            if ! kubectl rollout status deployment/testnet-$service --timeout=600s; then
              failed_deployments+=("$service")
            fi
          done

          if [ ${#failed_deployments[@]} -ne 0 ]; then
            echo "Failed to deploy: ${failed_deployments[*]}"
            exit 1
          fi
